apiVersion: v1
kind: Service

metadata:
  name: postgres-rag-ollama
  namespace: rag-app

spec:
  type: ClusterIP

  selector:
    app: postgres-rag-ollama

  ports:

    - name: frontend
      port: 8501
      targetPort: 8501
      protocol: TCP

    - name: backend
      port: 8000
      targetPort: 8000
      protocol: TCP