apiVersion: v1
kind: Service
metadata:
  name: postgres-rag-ollama
  namespace: rag-app

spec:
  type: NodePort

  selector:
    app: postgres-rag-ollama

  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30861
      protocol: TCP