apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-app

resources:
  - namespace.yaml
  - postgres.yaml
  - postgres-service.yaml
  - ollama.yaml
  - ollama-service.yaml
  - app-deployment.yaml
  - app-service.yaml
 