apiVersion: v1
kind: Service
metadata:
  name: postgres-rag-db
  namespace: rag-app

spec:
  type: ClusterIP

  selector:
    app: postgres-rag-db

  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP